// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Ix7HRKg9MoGGv_SnXu-Pqt8M24c86Yo',
    appId: '1:953616443674:web:21695e0fb8d7765677a4a3',
    messagingSenderId: '953616443674',
    projectId: 'elite-academy-7d7fe',
    authDomain: 'elite-academy-7d7fe.firebaseapp.com',
    storageBucket: 'elite-academy-7d7fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnaw0cikUTRmgVvSdM-XVyMQSvqr8f7ak',
    appId: '1:953616443674:android:92d41a798cbc6ad177a4a3',
    messagingSenderId: '953616443674',
    projectId: 'elite-academy-7d7fe',
    storageBucket: 'elite-academy-7d7fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhjKOSVEyt4D087rtSYA8qS77GFBMp3EY',
    appId: '1:953616443674:ios:b367c550a4c4e8a677a4a3',
    messagingSenderId: '953616443674',
    projectId: 'elite-academy-7d7fe',
    storageBucket: 'elite-academy-7d7fe.firebasestorage.app',
    iosBundleId: 'com.dinhInternational.luggageTracking',
  );
}
