# Uncomment this line to define a global platform for your project
platform :ios, '15.6'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_LOCATION=0',

      ]
    end
  end
  
  # Add BeaconPlus frameworks to the project
  project_path = 'Runner.xcodeproj'
  project = Xcodeproj::Project.open(project_path)
  
  # Get the Runner target
  runner_target = project.targets.find { |target| target.name == 'Runner' }
  
  if runner_target
    frameworks_group = project.main_group.find_subpath('Frameworks', true)
    
    # Add frameworks
    ['MTBeaconPlus.framework', 'iOSDFULibrary.framework', 'ZIPFoundation.framework'].each do |framework_name|
      framework_path = "Framworks/#{framework_name}"
      
      # Check if framework reference already exists
      unless frameworks_group.files.any? { |file| file.path == framework_path }
        framework_ref = frameworks_group.new_file(framework_path)
        runner_target.frameworks_build_phase.add_file_reference(framework_ref)
      end
    end
    
    # Add framework search paths
    runner_target.build_configurations.each do |config|
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '$(PROJECT_DIR)/Framworks'
    end
    
    project.save
  end
end
